# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0242224f8771b7354fce58ad944253ec6040add190f1b93d7615136a6f20d780351fc378dbdbb0e89e8b32b9589f8826241f67ac2748b2cbf5523b1086ca8000

test:
  secret_key_base: 4607d534b701b2c5fcc656e3663f97cb53f963fb03c005c8ea2d7d0bd3660fae4106e14c64f8f67e5030b1b1fedd593c909097787a57269a5b34dbca7d5ed439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
